language: python
python:
  - "3.6"
install:
  - sudo apt-get -y install freeglut3-dev ffmpeg
  - pipenv sync
  - pipenv sync --dev
script:
  - pipenv run xvfb-run -s "-screen 0 1400x900x24" python -m unittest discover
